name: Release

on:
  push:
    branches:
      - main
  # manual trigger
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn prepare

      - run: yarn prei18n:compile
        with:
          upload_sources: true
          download_translations: true
          create_pull_request: false
          push_translations: false
          localization_branch_name: main
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
          project_id: 458284
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn i18n:compile

      - run: yarn test
        if: success()
        env:
          JSON_RPC_PROVIDER: ${{ secrets.JSON_RPC_PROVIDER }}

      - run: yarn release
        if: success()
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
